export const SLIDE_LIST_REQUEST = 'SLIDE_LIST_REQUEST'
export const SLIDE_LIST_SUCCESS = 'SLIDE_LIST_SUCCESS'
export const SLIDE_LIST_FAIL = 'SLIDE_LIST_FAIL'

export const SLIDE_DETAILS_REQUEST = 'SLIDE_DETAILS_REQUEST'
export const SLIDE_DETAILS_SUCCESS = 'SLIDE_DETAILS_SUCCESS'
export const SLIDE_DETAILS_FAIL = 'SLIDE_DETAILS_FAIL'

export const SLIDE_CREATE_REQUEST = 'SLIDE_CREATE_REQUEST'
export const SLIDE_CREATE_SUCCESS = 'SLIDE_CREATE_SUCCESS'
export const SLIDE_CREATE_FAIL = 'SLIDE_CREATE_FAIL'
export const SLIDE_CREATE_RESET = 'SLIDE_CREATE_RESET'
